import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tailwindcss with Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main>
        <h1 className="font-bold text-slate-100">Hello world!</h1>
      </main>
    </>
  );
}
